language: scala
scala:
   - 2.12.7

script:
   - sbt clean coverage test coverageReport scalastyle scalafmt doc assembly
   - bash runbecomeraces.sh
   - bash runcallbackorder.sh

after_success:
   - bash <(curl -s https://codecov.io/bash)