language: scala
scala:
   - 2.12.6

script:
   - sbt clean coverage test coverageReport scalastyle doc assembly
   - bash runbecomeraces.sh
   - bash runbenchmarks.sh
   - bash runcallbackorder.sh

after_success:
   - bash <(curl -s https://codecov.io/bash)